sudo: false
language: java
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk7

script:
  - mvn -e clean install

after_success: test "${TRAVIS_PULL_REQUEST}" == "false" && ./scripts/upload-snapshot
